version: "3"

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  run:
    # watch: true
    # sources:
    #   - "**/*.go"
    cmds:
      - nodemon -x go run main.go --signal SIGKILL -e go --verbose
  mockgen-intall:
    cmds:
      - brew install mockery
      - brew upgrade mockery
  test:
    cmds:
      - go test ./internal/core/service
