// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: manager-account/manager-account.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManagerAccountClient is the client API for ManagerAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerAccountClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Sends another greeting
	Get(ctx context.Context, in *GetManagerRequest, opts ...grpc.CallOption) (*GetManagerResponse, error)
}

type managerAccountClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerAccountClient(cc grpc.ClientConnInterface) ManagerAccountClient {
	return &managerAccountClient{cc}
}

func (c *managerAccountClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/manager_account.ManagerAccount/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerAccountClient) Get(ctx context.Context, in *GetManagerRequest, opts ...grpc.CallOption) (*GetManagerResponse, error) {
	out := new(GetManagerResponse)
	err := c.cc.Invoke(ctx, "/manager_account.ManagerAccount/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerAccountServer is the server API for ManagerAccount service.
// All implementations must embed UnimplementedManagerAccountServer
// for forward compatibility
type ManagerAccountServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Sends another greeting
	Get(context.Context, *GetManagerRequest) (*GetManagerResponse, error)
	mustEmbedUnimplementedManagerAccountServer()
}

// UnimplementedManagerAccountServer must be embedded to have forward compatible implementations.
type UnimplementedManagerAccountServer struct {
}

func (UnimplementedManagerAccountServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedManagerAccountServer) Get(context.Context, *GetManagerRequest) (*GetManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedManagerAccountServer) mustEmbedUnimplementedManagerAccountServer() {}

// UnsafeManagerAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerAccountServer will
// result in compilation errors.
type UnsafeManagerAccountServer interface {
	mustEmbedUnimplementedManagerAccountServer()
}

func RegisterManagerAccountServer(s grpc.ServiceRegistrar, srv ManagerAccountServer) {
	s.RegisterService(&ManagerAccount_ServiceDesc, srv)
}

func _ManagerAccount_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerAccountServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_account.ManagerAccount/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerAccountServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerAccount_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerAccountServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_account.ManagerAccount/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerAccountServer).Get(ctx, req.(*GetManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerAccount_ServiceDesc is the grpc.ServiceDesc for ManagerAccount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerAccount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager_account.ManagerAccount",
	HandlerType: (*ManagerAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ManagerAccount_SayHello_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ManagerAccount_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager-account/manager-account.proto",
}
